module.exports = [
  "heta gedhara innavaa",
  "mata nam heta enna venne naee. mata office yanna thiyenavaa.",
  "adha gedhara giyoth, eeka anivarenma evannam.",
  "oyagee asaniipee adudha?",
  "oyaa adha school ennama onee",
  "mama heta vaeda karannam",
  "oyaa hari place ekata gihin naehae",
  "jaya veevaa!",
  "mama aavaa kiyalaa eyaata kiyanavadha?",
  "gaetaluvak naehae. mama baara gannam.",
  "karuNaakaralaa ooka mata dhenna puluvandha?",
  "adoo mehe varen!",
  "mama dhaen kaeema kanavaa.",
  "himin yanna",
  "heta api loku vaedak karanna laeesthi velaa inne",
  "ov ov",
  "api issara methana sellam kalaa",
  "mama mee dhaen pothak kiyavanavaa.",
  "api heta methana lunch gannavaa",
  "kavadhaavath eeka epaa.",
  "mama adha Movie ekak balanna yanavaa",
  "Api adha havasata vaeva balanna yamu",
  "karuNaakara ooka othanin thiyanna epaa. anee kiyanadhea ahapan!",
  "mee gaena api eyaa (magee akkaa) ekka kathaa karamu nedha?",
  "adoo siraavatama ehema unaadha?",
  "mama thaama inne eliyee. adha gedhara giyoth, eeka anivarenma evannam. eeka oyaata evvoth adhama hadhala dhenna. oyaa adhama hadhala dhunnoth mata puluvan eka magee yaaluvata yavanna. If that happens, we'll get results tomorrow. lakuNu hambunoth apita puluvan iiLaga vaeda tika ikmanatama patan gena karagena yanna.",
  "adha 2026/01/29 venidhaa. 7.40 AM venakota carrot 1kg k USD 1.35 k uNaa.",
  "adhama Email ekak dhaemmoth vaedee karaganna puluvan veyi.",
  "haemooma adha havasata campus ekee canteen ekata enna discussion ekakata.",
  "magee NIC eka naethi velaa",
  "mee gaena api Lecture (dhulini madam) ekka kathaa karamu nedha?",
  "heta udheema vahinavalu. mama enne naehae eeka nisaa",
  "adharaeetamamagedharayannathamayihithagenainne",
  "apee  ayiyaa   adha ennen  naehae",
  "@@@@****",
  "உயிரெழுத்துக்கள்",
  "mama sathuten 😀😃😄",
  "ma ma go dak dhura inne",
  "mamaaaa meheeee innee",
  "I am testing this software",
  "ma@ma meeka# pariika$Shaa karanavaa",
  "apii wenaqata sellan krnne methana",
  "mama anivaarenma heta gedhara innavaa",
  "mama thaama inne eliyee. adha gedhara giyoth, eeka anivarenma evannam. eeka oyaata evvoth adhama hadhala dhenna. oyaa adhama hadhala dhunnoth mata puluvan eka magee yaaluvata yavanna.",
  "kavadhaavath eeka epaa."
];
